Attendance/Controllers/othersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Attendance.Models;
using System.Data.SqlClient;

namespace Attendance.Controllers
{
    public class othersController : Controller
    {
        private othrZKAccessEntities4 db = new othrZKAccessEntities4();

        //
        // GET: /others/

        public ActionResult Index()
        {
            return View(db.otherts.ToList());
        }
        //**************************************************************************

        public ActionResult searchothers()
        {
            return View();
        }
        public ActionResult othrs(string the_inputdate)
        {

            Session["thedate1"] = the_inputdate;



            SqlParameter the_input_date11 = new SqlParameter("the_inputdate", the_inputdate);



            object[] parameters = new object[] { the_input_date11};


            using (var context = new othrZKAccessEntities4())
            {
                var data = context.otherts.SqlQuery("[dbo].[getothers] @the_inputdate", parameters);


                return View("Index", data.ToList());

            }
        }

        //**************************************************************************
        //
        // GET: /others/Details/5

        public ActionResult Details(long id = 0)
        {
            othert othert = db.otherts.Find(id);
            if (othert == null)
            {
                return HttpNotFound();
            }
            return View(othert);
        }

        //
        // GET: /others/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /others/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(othert othert)
        {
            if (ModelState.IsValid)
            {
                db.otherts.Add(othert);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(othert);
        }

        //
        // GET: /others/Edit/5

        public ActionResult Edit(long id = 0)
        {
            othert othert = db.otherts.Find(id);
            if (othert == null)
            {
                return HttpNotFound();
            }
            return View(othert);
        }

        //
        // POST: /others/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(othert othert)
        {
            if (ModelState.IsValid)
            {
                db.Entry(othert).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(othert);
        }

        //
        // GET: /others/Delete/5

        public ActionResult Delete(long id = 0)
        {
            othert othert = db.otherts.Find(id);
            if (othert == null)
            {
                return HttpNotFound();
            }
            return View(othert);
        }

        //
        // POST: /others/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            othert othert = db.otherts.Find(id);
            db.otherts.Remove(othert);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Attendance/Views/others/Create.cshtml
@model Attendance.Models.othert

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>othert</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.thedate2)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.thedate2)
            @Html.ValidationMessageFor(model => model.thedate2)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.thetime2)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.thetime2)
            @Html.ValidationMessageFor(model => model.thetime2)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.pin)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.pin)
            @Html.ValidationMessageFor(model => model.pin)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.device_name2)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.device_name2)
            @Html.ValidationMessageFor(model => model.device_name2)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DEPTNAME)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DEPTNAME)
            @Html.ValidationMessageFor(model => model.DEPTNAME)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Attendance/Views/others/Delete.cshtml
@model Attendance.Models.othert

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>othert</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.thedate2)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.thedate2)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.thetime2)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.thetime2)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.pin)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.pin)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.device_name2)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.device_name2)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DEPTNAME)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DEPTNAME)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Attendance/Views/others/Details.cshtml
@model Attendance.Models.othert

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>othert</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.thedate2)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.thedate2)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.thetime2)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.thetime2)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.pin)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.pin)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.device_name2)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.device_name2)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DEPTNAME)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DEPTNAME)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Attendance/Views/others/Edit.cshtml
@model Attendance.Models.othert

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>othert</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.thedate2)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.thedate2)
            @Html.ValidationMessageFor(model => model.thedate2)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.thetime2)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.thetime2)
            @Html.ValidationMessageFor(model => model.thetime2)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.pin)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.pin)
            @Html.ValidationMessageFor(model => model.pin)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.device_name2)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.device_name2)
            @Html.ValidationMessageFor(model => model.device_name2)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DEPTNAME)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DEPTNAME)
            @Html.ValidationMessageFor(model => model.DEPTNAME)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        @Html.HiddenFor(model => model.id)

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Attendance/Views/others/Index.cshtml
@model IEnumerable<Attendance.Models.othert>

@{
    ViewBag.Title = "Index";
}

<h2>إستثناءات الحضور والانصراف</h2>
<style>
    th, td {
        padding: 15px;
        text-align: right;
        font-family: 'Arial Rounded MT';
        font-weight: 500;
        border-bottom: 1px solid #ddd;
        border-right: 1px solid #ddd;
    }

    th {
        background-color: #4CAF50;
        color: black;
        font-style: normal;
    }

    table {
        font-size: 20px;
        border: 1px solid black;
    }
</style>

<table class="table table-striped">
    <tr style="font-weight:200;color:black">
        <th>
التاريخ        </th>
        <th>
الوقت        </th>
        <th>
الكود الوظيفى        </th>
        <th>
الماكينه
                </th>
        <th>
القطاع        </th>
        <th>
            الاسم
        </th>

    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.thedate2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.thetime2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.pin)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.device_name2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DEPTNAME)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>

        </tr>
}

</table>

Attendance/Views/others/searchothers.cshtml
@{
    ViewBag.Title = "إنصراف فقط";
}

<h2>إستثناءات الحضور والانصراف فقط</h2>


@using (Html.BeginForm("othrs", "others"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)


    <div>
        اختار التاريخ
        <br />        من @Html.TextBox("the_inputdate", "", new { @autocomplete = "off" })
        <br />  <input type="submit" value="search" />

    </div>







}

<div>
    <a href="/home/index">Back To Home</a>
</div>





@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


<script type="text/javascript">
    $(document).ready(function () {
        $("#the_inputdate").datepicker({

            dateFormat: "yy-mm-dd"
        });
    });
</script>