Attendance/Controllers/AttendanceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Attendance.Models;


namespace Attendance.Controllers
{
    public class AttendanceController : Controller
    {
        private ZKAccessEntities2 db = new ZKAccessEntities2();

        //
   //     public ActionResult absence(string the_input_date)
  //      {
   //         using (var context = new ZKAccessEntities2())
     //       {
      //          var data = context.absence.SqlQuery("[dbo].[absence]@the_input_date", new SqlParameter("the_input_date", the_input_date));
       //         return View("Index2", data.ToList());

         //   }
      //  }
 


        // GET: /Attendance/
                [Authorize()]

        public ActionResult Index()
        {
            return View(db.attendancevs.ToList());
        }
           public ActionResult Index2()
        {
            return View(db.attendancevs.ToList());
        }
           public ActionResult Index3()
           {
               return View(db.attendancevs.ToList());
           }



        //---------------------
           public ActionResult Index4()
           {
               return View(db.attendancevs.ToList());
           }
        //search 1
                        [Authorize()]

        public ActionResult search()
        {

            return View();
        }
                        [Authorize()]

        public ActionResult search1(string employeecode1, string employeecode12)
        {
            Session["employeecode1"] = employeecode1;
            var test1 = db.attendancevs.Where(t => t.atttime.Contains(employeecode1) && t.DEPTNAME.Contains(employeecode12));

            return View("Index2", test1.ToList());
        }
        //
        //search 2
                        [Authorize()]

        public ActionResult search2()
        {

            return View();
        }

        public ActionResult search22(string employeecode, string employeecode2)
        {
            Session["employeecode"] = employeecode;
            var test1 = db.attendancevs.Where(t => t.atttime.StartsWith(employeecode) && t.Badgenumber.StartsWith(employeecode2));

            return View("Index", test1.ToList());
        }
        //
        //search 3
                        [Authorize()]

        public ActionResult search3()
        {

            return View();
        }

        //------------------------------------------------------------------------------------

                        public ActionResult searchall()
                        {

                            return View();
                        }

                        public ActionResult allattendance(string attenddate)
                        {
                            Session["attenddate"] = attenddate;
                            var test1 = db.attendancevs.Where(t => t.atttime.StartsWith(attenddate));

                            return View("Index4", test1.ToList());
                        }
        
        
        
        //-----------------------------------------------------------------------------------



 




                        [Authorize()]

        public ActionResult search33(string employeecode3, string employeecode32)
        {
            Session["employeecode3"] = employeecode3;    
            var test1 = db.attendancevs.Where(t => t.atttime.StartsWith(employeecode3) && t.device_name.Contains(employeecode32));

            return View("Index3", test1.ToList());
        }
        //
        // GET: /Attendance/Details/5
                        [Authorize()]

        public ActionResult Details(string id = null)
        {
            attendancev attendancev = db.attendancevs.Find(id);
            if (attendancev == null)
            {
                return HttpNotFound();
            }
            return View(attendancev);
        }

        //
        // GET: /Attendance/Create
                        [Authorize()]

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Attendance/Create
                        [Authorize()]

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(attendancev attendancev)
        {
            if (ModelState.IsValid)
            {
                db.attendancevs.Add(attendancev);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(attendancev);
        }

        //
        // GET: /Attendance/Edit/5

        public ActionResult Edit(string id = null)
        {
            attendancev attendancev = db.attendancevs.Find(id);
            if (attendancev == null)
            {
                return HttpNotFound();
            }
            return View(attendancev);
        }

        //
        // POST: /Attendance/Edit/5
                        [Authorize()]

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(attendancev attendancev)
        {
            if (ModelState.IsValid)
            {
                db.Entry(attendancev).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(attendancev);
        }

        //
        // GET: /Attendance/Delete/5
                        [Authorize()]

        public ActionResult Delete(string id = null)
        {
            attendancev attendancev = db.attendancevs.Find(id);
            if (attendancev == null)
            {
                return HttpNotFound();
            }
            return View(attendancev);
        }

        //
        // POST: /Attendance/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            attendancev attendancev = db.attendancevs.Find(id);
            db.attendancevs.Remove(attendancev);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public object employeecode1 { get; set; }
    }
}

Attendance/Views/Attendance/Create.cshtml
@model Attendance.Models.attendancev

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>attendancev</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.atttime)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.atttime)
            @Html.ValidationMessageFor(model => model.atttime)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.device_name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.device_name)
            @Html.ValidationMessageFor(model => model.device_name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Badgenumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Badgenumber)
            @Html.ValidationMessageFor(model => model.Badgenumber)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DEPTNAME)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DEPTNAME)
            @Html.ValidationMessageFor(model => model.DEPTNAME)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DEFAULTDEPTID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DEFAULTDEPTID)
            @Html.ValidationMessageFor(model => model.DEFAULTDEPTID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Expr1)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Expr1)
            @Html.ValidationMessageFor(model => model.Expr1)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DEPTID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DEPTID)
            @Html.ValidationMessageFor(model => model.DEPTID)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Attendance/Views/Attendance/Delete.cshtml
@model Attendance.Models.attendancev

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>attendancev</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.atttime)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.atttime)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.device_name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.device_name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Badgenumber)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Badgenumber)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DEPTNAME)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DEPTNAME)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DEFAULTDEPTID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DEFAULTDEPTID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Expr1)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Expr1)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DEPTID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DEPTID)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Attendance/Views/Attendance/Details.cshtml
@model Attendance.Models.attendancev

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>attendancev</legend>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.atttime)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.atttime)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.device_name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.device_name)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Badgenumber)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Badgenumber)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.DEPTNAME)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DEPTNAME)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.DEFAULTDEPTID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DEFAULTDEPTID)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Expr1)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Expr1)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.DEPTID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DEPTID)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Attendance/Views/Attendance/Edit.cshtml
@model Attendance.Models.attendancev

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>attendancev</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.atttime)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.atttime)
            @Html.ValidationMessageFor(model => model.atttime)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.device_name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.device_name)
            @Html.ValidationMessageFor(model => model.device_name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Badgenumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Badgenumber)
            @Html.ValidationMessageFor(model => model.Badgenumber)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DEPTNAME)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DEPTNAME)
            @Html.ValidationMessageFor(model => model.DEPTNAME)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DEFAULTDEPTID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DEFAULTDEPTID)
            @Html.ValidationMessageFor(model => model.DEFAULTDEPTID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Expr1)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Expr1)
            @Html.ValidationMessageFor(model => model.Expr1)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DEPTID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DEPTID)
            @Html.ValidationMessageFor(model => model.DEPTID)
        </div>

        @Html.HiddenFor(model => model.id)

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Attendance/Views/Attendance/Index.cshtml
@model IEnumerable<Attendance.Models.attendancev>
<style>
    #preloader {
        position: fixed;
        left: 0;
        top: 0;
        z-index: 999;
        width: 100%;
        height: 100%;
        overflow: visible;
        background: #fff;
    }

    #ldr {
        position: fixed;
        top: 50%;
        left: 50%;
        margin-top: -50px;
        margin-left: -100px;
    }
</style>



<div id="preloader">
    <img src="~/Images/wait.gif" height="80" width="100" id="ldr" />
</div>
@{
    ViewBag.Title = "نتيجة البحث ";
}

@{
    string p1 = (string)System.Web.HttpContext.Current.Session["employeecode"];
}

<br />
<h2>نتيجة البحث</h2>
@p1 عن تاريخ
<style>
    th, td {
        padding: 15px;
        text-align: left;
        font-family: 'Arial Rounded MT';
        font-weight: 500;
        border-bottom: 1px solid #ddd;
        border-right: 1px solid #ddd;
    }

    th {
        background-color: #4CAF50;
        color: white;
    }

    table {
        font-size: 14px;
        border: 1px solid black;
    }
</style>

<table class="table table-striped">
    <tr>

        <th>
            التاريخ
        </th>
        <th>
            اسم الماكينه

        </th>
        <th>
            الكود الوظيفى

        </th>
        <th>
            القطاعات
        </th>
        <th>

            الوقت
        </th>
        <th>
            الاسم
        </th>


    </tr>

    @foreach (var item in Model.OrderBy(item => item.Name))
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.thedate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.device_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Badgenumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DEPTNAME)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.thetime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>

        </tr>
    }

</table>
<script>
    jQuery(document).ready(function ($) {
        $(window).load(function () {
            setTimeout(function () {
                $('#preloader').fadeIn('slow', function () { });
            }, -200000);



        });
        $(window).load(function () {
            setTimeout(function () {
                $('#preloader').delay(1600).fadeOut('slow', function () { });
            }, 20);



        });
    });
</script>

Attendance/Views/Attendance/search.cshtml
@{
    ViewBag.Title = "SEARCH AND REPORT";
}

<h2>SEARCH DB</h2>

@using (Html.BeginForm("search22", "Attendance"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)


    <div> 
        اختار التاريخ   @Html.TextBox("employeecode", "", new { @autocomplete = "off" })
    </div>
    <div>
      ادخل كود الموظف  @Html.TextBox("employeecode2", "", new { @autocomplete = "off" })
    </div>




        <input type="submit" value="search" />
  
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>
    $("#employeecode12").val("الأصول والأستثمار");


</script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#employeecode").datepicker({

            dateFormat: "Mdyy"
        });
    });
</script>

Attendance/Views/Attendance/search2.cshtml
@{
    ViewBag.Title = "SEARCH AND REPORT";
}
<h2>البحث باستخدام القطاعات</h2>

<h2>SEARCH DB</h2>
@{
    List<SelectListItem> listItems = new List<SelectListItem>();
    listItems.Add(new SelectListItem
        {
            Text = "الأصول والأستثمار",
            Value = "الأصول والأستثمار"
        });
    listItems.Add(new SelectListItem
        {
            Text = "إدارة  الاصول والموازنات",
            Value = "إدارة  الاصول والموازنات",
        });
    listItems.Add(new SelectListItem
        {
            Text = "القطاع المالى والمراجعه",
            Value = "القطاع المالى والمراجعه",
        });
    listItems.Add(new SelectListItem
        {
            Text = "الشئون الهندسية",
            Value = "الشئون الهندسية"
        });
    listItems.Add(new SelectListItem
    {
        Text = "الامن",
        Value = "الامن"
    });
    listItems.Add(new SelectListItem
    {
        Text = "الخدمات",
        Value = "الخدمات"
    });
    listItems.Add(new SelectListItem
    {
        Text = "الرقابة الداخلية",
        Value = "الرقابة الداخلية"
    });
    listItems.Add(new SelectListItem
    {
        Text = "الشئون التجارية",
        Value = "الشئون التجارية"
    });
    listItems.Add(new SelectListItem
    {
        Text = "الشئون الطبية",
        Value = "الشئون الطبية"
    });
    listItems.Add(new SelectListItem
    {
        Text = "المعلومات",
        Value = "المعلومات"
    });
    listItems.Add(new SelectListItem
    {
        Text = "AlexHI",
        Value = "AlexHI"
    });
    listItems.Add(new SelectListItem
    {
        Text = "EGOTH",
        Value = "EGOTH"
    });
    listItems.Add(new SelectListItem
    {
        Text = "ادارة الشركة والمتابعة",
        Value = "ادارة الشركة والمتابعة"
    });
    listItems.Add(new SelectListItem
    {
        Text = "التدريب والمعاهد",
        Value = "التدريب والمعاهد"
    });
    listItems.Add(new SelectListItem
    {
        Text = "الجراج",
        Value = "الجراج"
    });
    listItems.Add(new SelectListItem
    {
        Text = "الرقابة على الفنادق",
        Value = "الرقابة على الفنادق"
    });
    listItems.Add(new SelectListItem
    {
        Text = "الشئون الادارية",
        Value = "الشئون الادارية"
    });
    listItems.Add(new SelectListItem
    {
        Text = "العلاقات العامة",
        Value = "العلاقات العام"
    });
    
    listItems.Add(new SelectListItem
    {
        Text = "القانونى & العقود والشهر",
        Value = "القانونى & العقود والشهر"
    });

    listItems.Add(new SelectListItem
    {
        Text = "القانونى&القضاياوالتنفيذ",
        Value = "القانونى&القضاياوالتنفيذ"
    });
    listItems.Add(new SelectListItem
    {
        Text = "معاونى الخدمة",
        Value = "معاونى الخدمة"
    });
    listItems.Add(new SelectListItem
    {
        Text = "معهد الأسكندرية",
        Value = "معهد الأسكندرية"
    });
    listItems.Add(new SelectListItem
    {
        Text = "معهد الاقصر",
        Value = "معهد الاقصر"
    });
	listItems.Add(new SelectListItem
    {
        Text = "منطقة الاقصر",
        Value = "منطقة الاقصر"
    });
    listItems.Add(new SelectListItem
    {
        Text = "أمن الأقصر",
        Value = "أمن الأقصر"
    });
    listItems.Add(new SelectListItem
    {
        Text = "التخطيط والدراسات الاقتصادية",
        Value = "التخطيط والدراسات الاقتصادية"
    });
	listItems.Add(new SelectListItem
	    {
        Text = "الأسكندرية -القصر",
        Value = "الأسكندرية -القصر"
    });
	
	listItems.Add(new SelectListItem
	    {
        Text = "معهد الاسكندرية",
        Value = "معهد الاسكندرية"
    });
			listItems.Add(new SelectListItem
	    {
        Text = "أمن الأسكندرية",
        Value = "أمن الأسكندرية"
    });
}
@using (Html.BeginForm("search1", "Attendance"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div>
        اختار التاريخ     @Html.TextBox("employeecode1", "", new { @autocomplete = "off" })
    </div>

    <div>
     القطاعات التى تم اختيارها   @Html.DropDownList("depname", new SelectList(listItems, "Value", "Text"))
    </div>
    <div>
    اختار القطاعات  @Html.TextBox("employeecode12", "", new { @autocomplete = "off" ,@val="الشئون الماليه"})
    </div>






        <input type="submit" value="search" />
   
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


<script type="text/javascript">
    $(document).ready(function () {
        $('#employeecode1').change(function () {
            sessionStorage.setItem("employeecode1",document.getElementById("employeecode1").value);
        });
        document.getElementById("employeecode1").value = sessionStorage.getItem("employeecode1");
        $("#employeecode1").datepicker({

            dateFormat: "Mdyy"
        });
    });





</script>
<script>
    $(document).ready(function () {
        $('#depname').change(function () {
            sessionStorage.setItem("employeecode12", document.getElementById("depname").value);





        });
        document.getElementById("employeecode12").value = sessionStorage.getItem("employeecode12");

    });
</script>
<script>

    $(document).ready(function () {
        console.log("ready!");

   //     $('#depname').change(function () {
     //       sessionStorage.setItem("employeecode1",toString(document.getElementById("employeecode1").value))
        //});
       // document.getElementById("employeecode1").value = sessionStorage.getItem("employeecode1")
   // $("#employeecode12").val("الأصول والأستثمار");
 //   window.onload = function () {
        $('#depname').hover(function () {
            var depname = $('#depname').val();
            $("#employeecode12").val(depname);
        });
        //function storedata() {
        //    if (typeof (Storage) !== "undefined") {
        //        var employeecode1 = document.getElementById("employeecode1").value;
        //        var depname = document.getElementById("depname").value;
        //        var employeecode12 = document.getElementById("employeecode12").value;
        //        sessionStorage.depname = depname;
        //        sessionStorage.employeecode12 = employeecode12;
        //        sessionStorage.employeecode1 = employeecode1;


        //        console.log("Your datas restored");
        //    } else {
        //        console.log("Sorry, your browser does not support web storage...");
        //    }
        //}
        //storedata();
        //if (sessionStorage.employeecode1 && sessionStorage.depname && sessionStorage.employeecode12) {
        //    document.getElementById("employeecode1").value = sessionStorage.employeecode1;
        //    document.getElementById("depname").value = sessionStorage.depname;
        //    document.getElementById("employeecode12").value = sessionStorage.employeecode12;
        //}
    });



</script>

Attendance/Views/Attendance/search3.cshtml
@{
    ViewBag.Title = "SEARCH AND REPORT";
}
<h1>البحث باستخدام اسم الماكينه</h1>
<h2>SEARCH DB</h2>
@{
    List<SelectListItem> listItems = new List<SelectListItem>();
    listItems.Add(new SelectListItem
        {
            Text = "التوفيقية",
            Value = "التوفيقية"
        });
    listItems.Add(new SelectListItem
        {
            Text = "الفوالة_10",
            Value = "الفوالة_10",
        });
    listItems.Add(new SelectListItem
        {
            Text = "الفوالة_8",
            Value = "الفوالة_8"
        });
   
    listItems.Add(new SelectListItem
    {
        Text = "جاردن _6",
        Value =  "جاردن _6"
    });
    listItems.Add(new SelectListItem
    {
        Text = "جاردن _9",
        Value = "جاردن _9"
    });
   
    listItems.Add(new SelectListItem
    {
        Text = "سيتي بنك",
        Value = "سيتي بنك"
    });
    listItems.Add(new SelectListItem
    {
        Text = "قصر النيل",
        Value = "قصر النيل"
    });
    listItems.Add(new SelectListItem
    {
        Text = "مهندسين_7",
        Value = "مهندسين_7"
    });
    listItems.Add(new SelectListItem
    {
        Text = "مهندسين_8",
        Value = "مهندسين_8"
    });


}
@using (Html.BeginForm("search33", "Attendance"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div>
      اختار التاريخ  @Html.TextBox("employeecode3", "", new { @autocomplete = "off" })
        </div>

    <div>
        اختار اسم الماكينه  @Html.DropDownList("depname", new SelectList(listItems, "Value", "Text"))
    </div>
    <div>
        اسم الماكينه      @Html.TextBox("employeecode32", "", new { @autocomplete = "off" })
    </div>






        <input type="submit" value="search" />

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script>
    $("#employeecode12").val("الأصول والأستثمار");


</script>

<script type="text/javascript">
    $(document).ready(function () {
        $("#employeecode3").datepicker({

            dateFormat: "Mdyy"
        });
    });
</script>
<script>
    $('#depname').change(function () {
        var depname = $('#depname').val();
        $("#employeecode32").val(depname);
    });

</script>
<script>
    $("#employeecode32").val("التوفيقية");
</script>

Attendance/Views/Attendance/searchall.cshtml
@{
    ViewBag.Title = "SEARCH AND REPORT";
}

<h2>SEARCH DB</h2>

@using (Html.BeginForm("allattendance", "Attendance"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)


    <div>
        اختار التاريخ   @Html.TextBox("attenddate", "", new { @autocomplete = "off" })
    </div>





    <input type="submit" value="search" />

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


<script type="text/javascript">
    $(document).ready(function () {
        $("#attenddate").datepicker({

            dateFormat: "Mdyy"
        });
    });
</script>