Attendance/Controllers/byinterController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Attendance.Models;
using System.Data.SqlClient;

namespace Attendance.Controllers
{
    public class byinterController : Controller
    {
        private AttLoginEntities1 db = new AttLoginEntities1();

        //
        // GET: /byinter/

        public ActionResult Index()
        {
            return View(db.byintervals.ToList());
        }

        //
        // GET: /byinter/Details/5

        public ActionResult Details(long id = 0)
        {
            byinterval byinterval = db.byintervals.Find(id);
            if (byinterval == null)
            {
                return HttpNotFound();
            }
            return View(byinterval);
        }

        //
        // GET: /byinter/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /byinter/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(byinterval byinterval)
        {
            if (ModelState.IsValid)
            {
                db.byintervals.Add(byinterval);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(byinterval);
        }

        //
        [HttpPost]
        [ValidateAntiForgeryToken]

        // GET: /byinter/Edit/5

        public ActionResult Edit(long id = 0)
        {
            byinterval byinterval = db.byintervals.Find(id);
            if (byinterval == null)
            {
                return HttpNotFound();
            }
            return View(byinterval);
        }

        //**************************
        public ActionResult byinterval(string frominputdate, string toinputdate, string empcode)
        {

            Session["frominputdate"] = frominputdate;
            Session["toinputdate"] = toinputdate;
            Session["empcode"] = empcode;



            if (frominputdate == "" || toinputdate == ""||empcode == "")
            {
                return View("notfound");


            }
            SqlParameter frominputdate1 = new SqlParameter("frominputdate", frominputdate);
            SqlParameter toinputdate1 = new SqlParameter("toinputdate", toinputdate);
            SqlParameter empcode1 = new SqlParameter("empcode", empcode);



            object[] parameters = new object[] { frominputdate1, toinputdate1, empcode1 };


            using (var context = new AttLoginEntities1())
            {
                var data = context.byintervals.SqlQuery("[dbo].[getbyinterval] @frominputdate, @toinputdate,@empcode", parameters);


                return View("Index", data.ToList());

            }
        }
        //============================
        public ActionResult byinterval2(string frominputdate, string toinputdate, string empcode)
        {

            Session["frominputdate"] = frominputdate;
            Session["toinputdate"] = toinputdate;
            Session["empcode"] = empcode;



            if (frominputdate == "" || toinputdate == "" || empcode == "")
            {
                return View("notfound");


            }
            SqlParameter frominputdate1 = new SqlParameter("frominputdate", frominputdate);
            SqlParameter toinputdate1 = new SqlParameter("toinputdate", toinputdate);
            SqlParameter empcode1 = new SqlParameter("empcode", empcode);



            object[] parameters = new object[] { frominputdate1, toinputdate1, empcode1 };


            using (var context = new AttLoginEntities1())
            {
                var data = context.byintervals.SqlQuery("[dbo].[getbyinterval2] @frominputdate, @toinputdate,@empcode", parameters);


                return View("Index2", data.ToList());

            }
        }
        // POST: /byinter/Edit/5
        public ActionResult searchbyinterval()
        {
            return View();
        }

        //----------------------

        public ActionResult searchbyinterval2()
        {
            return View();
        }

        //***************************
        //==================================================================================================================================================================
        public ActionResult searchbyinterval3()
        {
            return View();
        }

        public ActionResult byinterval3(string frominputdate, string toinputdate, string empcode)
        {

            Session["frominputdate"] = frominputdate;
            Session["toinputdate"] = toinputdate;
            Session["empcode"] = empcode;



            if (frominputdate == "" || toinputdate == "" || empcode == "")
            {
                return View("notfound");


            }
            SqlParameter frominputdate1 = new SqlParameter("frominputdate", frominputdate);
            SqlParameter toinputdate1 = new SqlParameter("toinputdate", toinputdate);
            SqlParameter empcode1 = new SqlParameter("empcode", empcode);



            object[] parameters = new object[] { frominputdate1, toinputdate1, empcode1 };


            using (var context = new AttLoginEntities1())
            {
                var data = context.byintervals.SqlQuery("[dbo].[getbyinterval2] @frominputdate, @toinputdate,@empcode", parameters);


                return View("Index3", data.ToList());

            }


        }
        //====================================================================================================================================================================
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(byinterval byinterval)
        {
            if (ModelState.IsValid)
            {
                db.Entry(byinterval).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(byinterval);
        }

        //
        // GET: /byinter/Delete/5

        public ActionResult Delete(long id = 0)
        {
            byinterval byinterval = db.byintervals.Find(id);
            if (byinterval == null)
            {
                return HttpNotFound();
            }
            return View(byinterval);
        }

        //
        // POST: /byinter/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            byinterval byinterval = db.byintervals.Find(id);
            db.byintervals.Remove(byinterval);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Attendance/Views/byinter/Create.cshtml
@model Attendance.Models.byinterval

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>byinterval</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.pin2)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.pin2)
            @Html.ValidationMessageFor(model => model.pin2)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.pin)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.pin)
            @Html.ValidationMessageFor(model => model.pin)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.thetime1)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.thetime1)
            @Html.ValidationMessageFor(model => model.thetime1)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.thetime2)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.thetime2)
            @Html.ValidationMessageFor(model => model.thetime2)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.device_name1)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.device_name1)
            @Html.ValidationMessageFor(model => model.device_name1)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.device_name2)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.device_name2)
            @Html.ValidationMessageFor(model => model.device_name2)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DEPTNAME)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DEPTNAME)
            @Html.ValidationMessageFor(model => model.DEPTNAME)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.thedate1)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.thedate1)
            @Html.ValidationMessageFor(model => model.thedate1)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Attendance/Views/byinter/Delete.cshtml
@model Attendance.Models.byinterval

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>byinterval</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.pin2)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.pin2)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.pin)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.pin)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.thetime1)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.thetime1)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.thetime2)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.thetime2)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.device_name1)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.device_name1)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.device_name2)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.device_name2)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DEPTNAME)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DEPTNAME)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.thedate1)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.thedate1)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Attendance/Views/byinter/Details.cshtml
@model Attendance.Models.byinterval

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>byinterval</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.pin2)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.pin2)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.pin)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.pin)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.thetime1)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.thetime1)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.thetime2)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.thetime2)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.device_name1)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.device_name1)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.device_name2)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.device_name2)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DEPTNAME)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DEPTNAME)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.thedate1)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.thedate1)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Attendance/Views/byinter/Edit.cshtml
@model Attendance.Models.byinterval

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>byinterval</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.pin2)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.pin2)
            @Html.ValidationMessageFor(model => model.pin2)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.pin)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.pin)
            @Html.ValidationMessageFor(model => model.pin)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.thetime1)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.thetime1)
            @Html.ValidationMessageFor(model => model.thetime1)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.thetime2)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.thetime2)
            @Html.ValidationMessageFor(model => model.thetime2)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.device_name1)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.device_name1)
            @Html.ValidationMessageFor(model => model.device_name1)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.device_name2)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.device_name2)
            @Html.ValidationMessageFor(model => model.device_name2)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DEPTNAME)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DEPTNAME)
            @Html.ValidationMessageFor(model => model.DEPTNAME)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        @Html.HiddenFor(model => model.id)

        <div class="editor-label">
            @Html.LabelFor(model => model.thedate1)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.thedate1)
            @Html.ValidationMessageFor(model => model.thedate1)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Attendance/Views/byinter/Index.cshtml
@model IEnumerable<Attendance.Models.byinterval>

@{
    ViewBag.Title = "Index";
}
@{var thediff = 15;}
@{var diff2 = 0;}
@{var diff1 = 0;}
<style>
    #preloader {
        position: fixed;
        left: 0;
        top: 0;
        z-index: 999;
        width: 100%;
        height: 100%;
        overflow: visible;
        background: #fff;
    }

    #ldr {
        position: fixed;
        top: 50%;
        left: 50%;
        margin-top: -50px;
        margin-left: -100px;
    }
</style>



<div id="preloader">
    <img src="~/Images/wait.gif" height="80" width="100" id="ldr" />
</div>
@{
    string frm = (string)System.Web.HttpContext.Current.Session["frominputdate"];
    string to = (string)System.Web.HttpContext.Current.Session["toinputdate"];
    string empc = (string)System.Web.HttpContext.Current.Session["empcode"];

    
}
<center>
    <h1>

        تقرير الحضور الخاص بالموظف
        @empc


    </h1>
    <br />
    <h1>
        @to                عن الفتره من             @frm           الى

    </h1></center>
<style>
    th, td {
        padding: 15px;
        text-align: right;
        font-family: 'Arial Rounded MT';
        font-weight: 500;
        border-bottom: 1px solid #ddd;
        border-right: 1px solid #ddd;
    }

    th {
        background-color: #4CAF50;
        color: black;
        font-style: normal;
    }

    table {
        font-size: 20px;
        border: 1px solid black;
    }
</style>
<table class="table table-striped">
    <tr>

     
        <th>
            وقت الانصراف
        </th>
        <th>
            وقت الحضور 
        </th>
        <th>
            ماكينة الانصراف
        </th>
        <th>
            ماكينة الحضور
        </th>
        <th>
            القطاع
        </th>
        <th>
تاريخ اليوم        </th>
        <th>

الاسم        </th>

    </tr>

    @foreach (var item in Model.OrderBy(item => item.thedate1))
    {
        
                    if (item.thetime2 != null && item.thetime1 != null)
            {
                //TimeSpan difference = item.thetime2.item.thetime1;

                diff2 = (int)(item.thetime2.Value.Hours);
                diff1 = (int)(item.thetime1.Value.Hours);
                thediff = (int)(diff2 - diff1);

            }
        if (thediff < 1) { 
        <tr>

            
            
            
          
            

                <td style="width:7px;">

                </td>
            
 

            <td>
                @Html.DisplayFor(modelItem => item.thetime1)
            </td>
}
            <td>
                @Html.DisplayFor(modelItem => item.device_name2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.device_name1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DEPTNAME)
            </td>
                @if (item.thedate1 == null)
                {

                    <td>
                        @Html.DisplayFor(modelItem => item.thedate2)
                    </td>

                }
                else
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.thedate1)
                    </td>
                }
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
     
        </tr>
            
        
        
        
        }
        else{
        <tr>

            
            
            
          
            

                <td style="width:7px;">

                    @Html.DisplayFor(modelItem => item.thetime2)
                </td>
            
 

            <td>
                @Html.DisplayFor(modelItem => item.thetime1)
            </td>
}
            <td>
                @Html.DisplayFor(modelItem => item.device_name2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.device_name1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DEPTNAME)
            </td>
                @if (item.thedate1 == null)
                {

                    <td>
                        @Html.DisplayFor(modelItem => item.thedate2)
                    </td>

                }
                else
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.thedate1)
                    </td>
                }
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
     
        </tr>
    }
    }
</table>
<script>
    jQuery(document).ready(function ($) {
        $(window).load(function () {
            setTimeout(function () {
                $('#preloader').fadeIn('slow', function () { });
            }, -200000);



        });
        $(window).load(function () {
            setTimeout(function () {
                $('#preloader').delay(1600).fadeOut('slow', function () { });
            }, 20);



        });
    });
</script>

Attendance/Views/byinter/searchbyinterval.cshtml
@{
    ViewBag.Title = "الغياب";
}

<h2>  حضور الفتره باستخدام الكود الوظيفى</h2>


@using (Html.BeginForm("byinterval", "byinter"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)


    <div>
        اختر تاريخ الفتره
        <br />        من @Html.TextBox("frominputdate", "", new { @autocomplete = "off" })

        <br />الى           @Html.TextBox("toinputdate", "", new { @autocomplete = "off" })

        <div>
         ادخل رقم الموظف  @Html.TextBox("empcode", "", new { @autocomplete = "off" })
        </div>
        <br />  <input type="submit" value="search" />
    </div>







}

<div>
    <a href="/home/index">Back To Home</a>
</div>





@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


<script type="text/javascript">
    $(document).ready(function () {
        $("#frominputdate").datepicker({

            dateFormat: "yy-mm-dd"
        });
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#toinputdate").datepicker({

            dateFormat: "yy-mm-dd"
        });
    });
</script>

Attendance/Views/byinter/searchbyinterval2.cshtml
@{
    ViewBag.Title = "";
}

<h2>حضور الفتره</h2>
@{
    List<SelectListItem> listItems = new List<SelectListItem>();
    
    listItems.Add(new SelectListItem
    {
        Text = "الجراج",
        Value = "الجراج"
    });
    

}

@using (Html.BeginForm("byinterval2", "byinter"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)


    <div>
        اختر تاريخ الفتره
        <br />        من @Html.TextBox("frominputdate", "", new { @autocomplete = "off" })

        <br />الى           @Html.TextBox("toinputdate", "", new { @autocomplete = "off" })
        <div>
             اختر القطاع  @Html.DropDownList("depname", new SelectList(listItems, "Value", "Text"))
        </div>

        <div>
            القطاعات التى تم اختيارها  @Html.TextBox("empcode", "", new { @autocomplete = "off" })
        </div>
        <br />  <input type="submit" value="search" />
    </div>







}

<div>
    <a href="/home/index">Back To Home</a>
</div>





@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


<script type="text/javascript">
    $(document).ready(function () {
        $("#frominputdate").datepicker({

            dateFormat: "yy-mm-dd"
        });
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#toinputdate").datepicker({

            dateFormat: "yy-mm-dd"
        });
    });
</script>
<script>
    $('#depname').change(function () {
        var depname = $('#depname').val();
        $("#empcode").val(depname);
    });

</script>
<script>
    $("#empcode").val($('#depname').val());


</script>

Attendance/Views/byinter/searchbyinterval3.cshtml
@{
    ViewBag.Title = "";
}

<h2>حضور الفتره</h2>
@{
    List<SelectListItem> listItems = new List<SelectListItem>();
    listItems.Add(new SelectListItem
        {
            Text = "الأصول والأستثمار",
            Value = "الأصول والأستثمار"
        });
    listItems.Add(new SelectListItem
        {
            Text = "الشئون المالية",
            Value = "الشئون المالية",
        });
    listItems.Add(new SelectListItem
        {
            Text = "الشئون الهندسية",
            Value = "الشئون الهندسية"
        });
    listItems.Add(new SelectListItem
    {
        Text = "الامن",
        Value = "الامن"
    });
    listItems.Add(new SelectListItem
    {
        Text = "الخدمات",
        Value = "الخدمات"
    });
    listItems.Add(new SelectListItem
    {
        Text = "الرقابة الداخلية",
        Value = "الرقابة الداخلية"
    });
    listItems.Add(new SelectListItem
    {
        Text = "الشئون التجارية",
        Value = "الشئون التجارية"
    });
    listItems.Add(new SelectListItem
    {
        Text = "الشئون الطبية",
        Value = "الشئون الطبية"
    });
    listItems.Add(new SelectListItem
    {
        Text = "المعلومات",
        Value = "المعلومات"
    });
    listItems.Add(new SelectListItem
    {
        Text = "AlexHI",
        Value = "AlexHI"
    });
    listItems.Add(new SelectListItem
    {
        Text = "EGOTH",
        Value = "EGOTH"
    });
    listItems.Add(new SelectListItem
    {
        Text = "ادارة الشركة والمتابعة",
        Value = "ادارة الشركة والمتابعة"
    });
    listItems.Add(new SelectListItem
    {
        Text = "التدريب والمعاهد",
        Value = "التدريب والمعاهد"
    });
    listItems.Add(new SelectListItem
    {
        Text = "الجراج",
        Value = "الجراج"
    });
    listItems.Add(new SelectListItem
    {
        Text = "الرقابة على الفنادق",
        Value = "الرقابة على الفنادق"
    });
    listItems.Add(new SelectListItem
    {
        Text = "الشئون الادارية",
        Value = "الشئون الادارية"
    });
    listItems.Add(new SelectListItem
    {
        Text = "العلاقات العامة",
        Value = "العلاقات العامة"
    });

    listItems.Add(new SelectListItem
    {
        Text = "القانونى & العقود والشهر",
        Value = "القانونى & العقود والشهر"
    });

    listItems.Add(new SelectListItem
    {
        Text = "القانونى&القضاياوالتنفيذ",
        Value = "القانونى&القضاياوالتنفيذ"
    });
    listItems.Add(new SelectListItem
    {
        Text = "معاونى الخدمة",
        Value = "معاونى الخدمة"
    });
    listItems.Add(new SelectListItem
    {
        Text = "معهد الأسكندرية",
        Value = "معهد الأسكندرية"
    });
    listItems.Add(new SelectListItem
    {
        Text = "معهد الاقصر",
        Value = "معهد الاقصر"
    });
    listItems.Add(new SelectListItem
    {
        Text = "التخطيط والدراسات الاقتصادية",
        Value = "التخطيط والدراسات الاقتصادية"
    });
		    listItems.Add(new SelectListItem
    {
        Text = "الأسكندرية -القصر",
        Value = "الأسكندرية -القصر"
    });
		listItems.Add(new SelectListItem
	    {
        Text = "معهد الاسكندرية",
        Value = "معهد الاسكندرية"
    });
		listItems.Add(new SelectListItem
	    {
        Text = "أمن الأسكندرية",
        Value = "أمن الأسكندرية"
    });
}

@using (Html.BeginForm("byinterval3", "byinter"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)


    <div>
        اختر تاريخ الفتره
        <br />        من @Html.TextBox("frominputdate", "", new { @autocomplete = "off" })

        <br />الى           @Html.TextBox("toinputdate", "", new { @autocomplete = "off" })
        <div>
            اختر القطاع  @Html.DropDownList("depname", new SelectList(listItems, "Value", "Text"))
        </div>

        <div>
            القطاعات التى تم اختيارها  @Html.TextBox("empcode", "", new { @autocomplete = "off" })
        </div>
        <br />  <input type="submit" value="search" />
    </div>







}

<div>
    <a href="/home/index">Back To Home</a>
</div>





@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


<script type="text/javascript">
    $(document).ready(function () {
        $("#frominputdate").datepicker({

            dateFormat: "yy-mm-dd"
        });
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#toinputdate").datepicker({

            dateFormat: "yy-mm-dd"
        });
    });
</script>
<script>
    $('#depname').change(function () {
        var depname = $('#depname').val();
        $("#empcode").val(depname);
    });

</script>
<script>
    $("#empcode").val($('#depname').val());


</script>